### ISSUE TITLE
Twitch has a problem showing Bits within IrcMessages

### ISSUE THREAD

**Issue by fmalk** [KararTY/dank-twitch-irc#18]
Hello,

First of all nice work keeping this lib updated. I'm happy my previous contribution was useful.

I'm facing an issue at my backend where it has become difficult to identify bits spent on messages.
This is not a bug per se, but I'd like to discuss a strategy to figure this out.
It all seems to work fine when there's a `Cheer`, but problem is Twitch rolled out a "highlighted message" feature where a user can spend 100 bits to highlight this message. At the json level, there's no info about the bits, but there's data about the message being highlighted. Take a look at the raw json:

```
{
  "rawSource": "@badge-info=;badges=;color=;display-name=xxxxx;emotes=;first-msg=0;flags=18-24:P.3/S.5;id=xxxx;mod=0;msg-id=highlighted-message;returning-chatter=0;room-id=xxxxx;subscriber=0;tmi-sent-ts=xxxx;turbo=0;user-id=xxxxx;user-type= xxxxxx.tmi.twitch.tv PRIVMSG #xxxx:a message",
  "ircPrefixRaw": "xxxx.tmi.twitch.tv",
  "ircPrefix": {
    "nickname": "xxxxx",
    "username": "xxxxx",
    "hostname": "xxxxx.tmi.twitch.tv"
  },
  "ircCommand": "PRIVMSG",
  "ircParameters": [
    "#xxxx",
    "a message"
  ],
  "ircTags": {
    "badge-info": "",
    "badges": "",
    "color": "",
    "display-name": "xxxxxx",
    "emotes": "",
    "first-ms g": "0",
    "flags": "18-24:P.3/S.5",
    "id": "xxxxx",
    "mod": "0",
    "msg-id": "highlighted-message",
    "return ing-chatter": "0",
    "room-id": "xxxxx",
    "subscriber": "0",
    "tmi-sent-ts": "xxxxx",
    "turbo": "0",
    "user-id": "xxxxx",
    "us er-type": ""
  },
  "channelName": "xxxx",
  "messageText": "a message",
  "isAction": false,
  "senderUsername": "xxxxxx",
  "senderUserID": "xxxxxx",
  "badgeInfo": [],
  "badgeInfoRaw": "",
  "badges": [],
  "badgesRaw": "",
  "colorRaw": "",
  "displayName": "xxxxxx",
  "emotes": [],
  "emotesRaw": "",
  "flags": [
    {
      "startIndex": 18,
      "endIndex": 25,
      "word": "xxxxx",
      "categories": [
        {
          "category": "P",
          "score": 3
        },
        {
          "category": "S",
          "score": 5
        }
      ]
    }
  ],
  "flagsRaw": "18-24:P.3/S.5",
  "messageID": "xxxxxx",
  "isMod": false,
  "isModRaw": "0",
  "channelID": "xxxxx",
  "serverTimestamp": "xxxxxx",
  "serverTimestampRaw": "xxxxx"
}
```

So there is a `"msg-id": "highlighted-message"` but that's it.
So, my questions:

- Should we tackle this "highlight" as some boolean flag at the parsed message?
- Should we worry about the bits? Other types of messages, like cheers, are working properly to others? I'm having trouble tracking spent bits.

I'm open to work on a PR if we agree it is indeed something worth working on. At this point I'm just parsing the tag/msg-id and doing my own logic.

**Comment by KararTY** [comment]
Can you specify how to do this "highlight with bits" feature and possibly a channel that has this? I can only find the "Cheer to pin" feature, is it the same one?

If so, the cheer to pin feature gives me this output:
```
@badge-info=;badges=;bits=100;color=#666666;display-name=PissRespect;emotes=;first-msg=0;flags=;id=beb1753a-166d-46cb-b101-fcc945345aab;mod=0;returning-chatter=0;room-id=11148817;subscriber=0;tmi-sent-ts=1701614103366;turbo=0;user-id=441347665;user-type= :pissrespect!pissrespect@pissrespect.tmi.twitch.tv PRIVMSG #pajlada :-tags Cheer100 testink
```

**Comment by fmalk** [comment]
It is close to "cheer to pin", and after looking for examples in other channels, it seems the streamer can set for how many bits to highlight:

![image](https://github.com/KararTY/dank-twitch-irc/assets/208820/08ef3650-656c-4ed9-a7fe-063f3d094a86)

At first I saw this at 100 bits, but at 12K bits that channel sure is pricey. But "highlight" doesn't pin, the message scrolls as usual.

I saw this other one while searching, UI isn't the same but it looks like the same feature:

![image](https://github.com/KararTY/dank-twitch-irc/assets/208820/11259b8d-d36d-4900-a114-cee2f7d52484)

At this point, my suggestion would be to look for that `"msg-id": "highlighted-message"` and create a "highlight": boolean property at IrcMessage, or PvtMessage.
However, I do realize I'm giving weak evidence about this rn, so I don't mind collecting more evidence to show a few more examples with logged json details.

**Comment by fmalk** [comment]
So, I found the channel that gave me the hint something was up, **jynxzi** - people leave lots of those

![image](https://github.com/KararTY/dank-twitch-irc/assets/208820/6f0e7344-741c-4f20-91fd-95d4400f2658)

So those three examples show there's a "redeem bits to hightlight" feature for streamers, value must be fixed at channel level, because there's no info about that at the raw message.

**Comment by KararTY** [comment]
Ah, I see the misunderstanding. Those are not bits, those are channel points you can earn by passively watching the channel. You get 100 to start off with on each channel when you first follow them. https://help.twitch.tv/s/article/viewer-channel-point-guide?language=en_US

If you have access to the broadcaster's token you can make use of Helix API https://dev.twitch.tv/docs/api/reference/#get-custom-reward and unfortunately I cannot point you to an official API that would let you get how many points each reward costs without the broadcaster's user access token.

The unofficial and "ToS breaking" API is the GQL endpoint the Twitch web client uses, it should give you how much each redemption costs.

If I'm still misunderstanding something, please let me know.

**Comment by fmalk** [comment]
@KararTY thanks for clarifying!
